# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogue_editor.ui'
#
# Created: Tue Dec 21 12:18:49 2010
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DialogueEditor(object):
    def setupUi(self, DialogueEditor):
        DialogueEditor.setObjectName("DialogueEditor")
        DialogueEditor.resize(800, 600)
        self.centralwidget = QtGui.QWidget(DialogueEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.views_widget = QtGui.QTabWidget(self.centralwidget)
        self.views_widget.setObjectName("views_widget")
        self.table_tab = QtGui.QWidget()
        self.table_tab.setObjectName("table_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.table_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sections_table_view = QtGui.QTableView(self.table_tab)
        self.sections_table_view.setObjectName("sections_table_view")
        self.verticalLayout_2.addWidget(self.sections_table_view)
        self.views_widget.addTab(self.table_tab, "")
        self.source_tab = QtGui.QWidget()
        self.source_tab.setObjectName("source_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.source_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.source_text_edit = CompletionTextEdit(self.source_tab)
        self.source_text_edit.setObjectName("source_text_edit")
        self.verticalLayout_3.addWidget(self.source_text_edit)
        self.views_widget.addTab(self.source_tab, "")
        self.chart_tab = QtGui.QWidget()
        self.chart_tab.setObjectName("chart_tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.chart_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chart_graphics_view = QtGui.QGraphicsView(self.chart_tab)
        self.chart_graphics_view.setObjectName("chart_graphics_view")
        self.verticalLayout_4.addWidget(self.chart_graphics_view)
        self.views_widget.addTab(self.chart_tab, "")
        self.verticalLayout.addWidget(self.views_widget)
        DialogueEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DialogueEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        DialogueEditor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DialogueEditor)
        self.statusbar.setObjectName("statusbar")
        DialogueEditor.setStatusBar(self.statusbar)
        self.file_panel = QtGui.QDockWidget(DialogueEditor)
        self.file_panel.setObjectName("file_panel")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.file_list_view = QtGui.QListView(self.dockWidgetContents_2)
        self.file_list_view.setObjectName("file_list_view")
        self.verticalLayout_6.addWidget(self.file_list_view)
        self.file_panel.setWidget(self.dockWidgetContents_2)
        DialogueEditor.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.file_panel)
        self.context_panel = QtGui.QDockWidget(DialogueEditor)
        self.context_panel.setObjectName("context_panel")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.context_widget = QtGui.QStackedWidget(self.dockWidgetContents)
        self.context_widget.setObjectName("context_widget")
        self.table_page = QtGui.QWidget()
        self.table_page.setObjectName("table_page")
        self.horizontalLayout = QtGui.QHBoxLayout(self.table_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sections_tree_list_view = QtGui.QTreeView(self.table_page)
        self.sections_tree_list_view.setObjectName("sections_tree_list_view")
        self.horizontalLayout.addWidget(self.sections_tree_list_view)
        self.context_widget.addWidget(self.table_page)
        self.source_page = QtGui.QWidget()
        self.source_page.setObjectName("source_page")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.source_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.source_tree_list_view = QtGui.QTreeView(self.source_page)
        self.source_tree_list_view.setObjectName("source_tree_list_view")
        self.verticalLayout_7.addWidget(self.source_tree_list_view)
        self.context_widget.addWidget(self.source_page)
        self.chart_page = QtGui.QWidget()
        self.chart_page.setObjectName("chart_page")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.chart_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tools_list_view = QtGui.QListView(self.chart_page)
        self.tools_list_view.setObjectName("tools_list_view")
        self.verticalLayout_8.addWidget(self.tools_list_view)
        self.context_widget.addWidget(self.chart_page)
        self.verticalLayout_5.addWidget(self.context_widget)
        self.context_panel.setWidget(self.dockWidgetContents)
        DialogueEditor.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.context_panel)
        self.file_toolbar = QtGui.QToolBar(DialogueEditor)
        self.file_toolbar.setObjectName("file_toolbar")
        DialogueEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.file_toolbar)
        self.section_toolbar = QtGui.QToolBar(DialogueEditor)
        self.section_toolbar.setObjectName("section_toolbar")
        DialogueEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.section_toolbar)
        self.context_panel_action = QtGui.QAction(DialogueEditor)
        self.context_panel_action.setCheckable(True)
        self.context_panel_action.setChecked(True)
        self.context_panel_action.setObjectName("context_panel_action")
        self.file_panel_action = QtGui.QAction(DialogueEditor)
        self.file_panel_action.setCheckable(True)
        self.file_panel_action.setChecked(True)
        self.file_panel_action.setObjectName("file_panel_action")
        self.action_Manual = QtGui.QAction(DialogueEditor)
        self.action_Manual.setObjectName("action_Manual")
        self.new_action = QtGui.QAction(DialogueEditor)
        self.new_action.setObjectName("new_action")
        self.save_action = QtGui.QAction(DialogueEditor)
        self.save_action.setObjectName("save_action")
        self.save_as_action = QtGui.QAction(DialogueEditor)
        self.save_as_action.setObjectName("save_as_action")
        self.close_action = QtGui.QAction(DialogueEditor)
        self.close_action.setObjectName("close_action")
        self.quit_action = QtGui.QAction(DialogueEditor)
        self.quit_action.setObjectName("quit_action")
        self.dialogue_editor_help_action = QtGui.QAction(DialogueEditor)
        self.dialogue_editor_help_action.setObjectName("dialogue_editor_help_action")
        self.about_dialogue_editor_action = QtGui.QAction(DialogueEditor)
        self.about_dialogue_editor_action.setObjectName("about_dialogue_editor_action")
        self.about_qt_action = QtGui.QAction(DialogueEditor)
        self.about_qt_action.setObjectName("about_qt_action")
        self.open_action = QtGui.QAction(DialogueEditor)
        self.open_action.setObjectName("open_action")
        self.add_section_action = QtGui.QAction(DialogueEditor)
        self.add_section_action.setObjectName("add_section_action")
        self.remove_section_toolbar = QtGui.QAction(DialogueEditor)
        self.remove_section_toolbar.setObjectName("remove_section_toolbar")
        self.edit_section_action = QtGui.QAction(DialogueEditor)
        self.edit_section_action.setObjectName("edit_section_action")
        self.menu_File.addAction(self.new_action)
        self.menu_File.addAction(self.open_action)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.save_action)
        self.menu_File.addAction(self.save_as_action)
        self.menu_File.addAction(self.close_action)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.quit_action)
        self.menu_View.addAction(self.context_panel_action)
        self.menu_View.addAction(self.file_panel_action)
        self.menu_Help.addAction(self.dialogue_editor_help_action)
        self.menu_Help.addAction(self.about_dialogue_editor_action)
        self.menu_Help.addAction(self.about_qt_action)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.file_toolbar.addAction(self.new_action)
        self.file_toolbar.addAction(self.open_action)
        self.file_toolbar.addAction(self.close_action)
        self.section_toolbar.addAction(self.add_section_action)
        self.section_toolbar.addAction(self.edit_section_action)
        self.section_toolbar.addAction(self.remove_section_toolbar)

        self.retranslateUi(DialogueEditor)
        self.views_widget.setCurrentIndex(1)
        self.context_widget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DialogueEditor)

    def retranslateUi(self, DialogueEditor):
        DialogueEditor.setWindowTitle(QtGui.QApplication.translate("DialogueEditor", "Dialogue Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.views_widget.setTabText(self.views_widget.indexOf(self.table_tab), QtGui.QApplication.translate("DialogueEditor", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.views_widget.setTabText(self.views_widget.indexOf(self.source_tab), QtGui.QApplication.translate("DialogueEditor", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.views_widget.setTabText(self.views_widget.indexOf(self.chart_tab), QtGui.QApplication.translate("DialogueEditor", "Chart", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("DialogueEditor", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("DialogueEditor", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("DialogueEditor", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("DialogueEditor", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.file_panel.setWindowTitle(QtGui.QApplication.translate("DialogueEditor", "Open Files", None, QtGui.QApplication.UnicodeUTF8))
        self.file_toolbar.setWindowTitle(QtGui.QApplication.translate("DialogueEditor", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.section_toolbar.setWindowTitle(QtGui.QApplication.translate("DialogueEditor", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.context_panel_action.setText(QtGui.QApplication.translate("DialogueEditor", "&Context Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.file_panel_action.setText(QtGui.QApplication.translate("DialogueEditor", "&File Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Manual.setText(QtGui.QApplication.translate("DialogueEditor", "&Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.new_action.setText(QtGui.QApplication.translate("DialogueEditor", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.save_action.setText(QtGui.QApplication.translate("DialogueEditor", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.save_as_action.setText(QtGui.QApplication.translate("DialogueEditor", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.close_action.setText(QtGui.QApplication.translate("DialogueEditor", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_action.setText(QtGui.QApplication.translate("DialogueEditor", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.dialogue_editor_help_action.setText(QtGui.QApplication.translate("DialogueEditor", "Dialogue Editor Help", None, QtGui.QApplication.UnicodeUTF8))
        self.about_dialogue_editor_action.setText(QtGui.QApplication.translate("DialogueEditor", "About Dialogue Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.about_qt_action.setText(QtGui.QApplication.translate("DialogueEditor", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.open_action.setText(QtGui.QApplication.translate("DialogueEditor", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.add_section_action.setText(QtGui.QApplication.translate("DialogueEditor", "Add Section", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_section_toolbar.setText(QtGui.QApplication.translate("DialogueEditor", "Remove Section", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_section_action.setText(QtGui.QApplication.translate("DialogueEditor", "Edit Section", None, QtGui.QApplication.UnicodeUTF8))

from custom_widgets import CompletionTextEdit
